# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

movies = [{:title => 'Apostle', :rating => 'Netflix', :release_date => '12-Oct-2018', :imgurl => 'apostle_poster.jpg', :favcounter => 0, :description => "In 1905, a drifter on a dangerous mission to rescue his kidnapped sister tangles with a sinister religious cult on an isolated island.", :price => "$8.99 per month"},
    	  {:title => 'Like Father', :rating => 'Netflix', :release_date => '3-Aug-2018', :imgurl => 'like_father.jpg', :favcounter => 0, :description => "After she's left at the altar, a workaholic advertising executive ends up on her Caribbean honeymoon cruise with her estranged father.", :price => "$8.99 per month"},
    	  {:title => 'Outlaw King', :rating => 'Netflix', :release_date => '9-Nov-2018', :imgurl => 'outlaw_king_poster.jpg', :favcounter => 0,:description => "A true David vs. Goliath story of how the 14th century Scottish 'Outlaw King' Robert the Bruce used cunning and bravery to defeat the much larger and better equipped occupying English army.", :price => "$8.99 per month"},
      	  {:title => 'A Land Imagined', :rating => 'Netflix', :release_date => '12-Apr-2019', :imgurl => 'imagined_land.jpg', :favcounter => 0,:description => "A lonely construction worker from China goes missing at a Singapore land reclamation site, and a sleepless police investigator must put himself in the mind of the migrant to uncover the truth beneath all that sand.", :price => "$8.99 per month"},
      	  {:title => 'The Perfect Date', :rating => 'Netflix', :release_date => '12-Apr-2019', :imgurl => 'perfect_date.jpg', :favcounter => 0, :description => "To save up for college, Brooks Rattigan creates an app where anyone can pay him to play the perfect stand-in boyfriend for any occasion.", :price => "$8.99 per month"},
      	  {:title => 'The Silence', :rating => 'Netflix', :release_date => '10-Apr-2019', :imgurl => 'the_silence.jpg', :favcounter => 0, :description => "When the world is under attack from terrifying creatures who hunt their human prey by sound, 16-year old Ally Andrews (Kiernan Shipka), who lost her hearing at 13, and her family seek refuge in a remote haven.", :price => "$8.99 per month"},
      	  {:title => 'Roma', :rating => 'Netflix', :release_date => '21-Nov-2018', :imgurl => 'roma.jpg', :favcounter => 0, :description => "A year in the life of a middle-class family's maid in Mexico City in the early 1970s.", :price => "$8.99 per month"},
      	  {:title => 'Mother!', :rating => 'Hulu', :release_date => '15-Sep-2017', :imgurl => 'mother.jpg', :favcounter => 0, :description => "A couple's relationship is tested when uninvited guests arrive at their home, disrupting their tranquil existence.", :price => "$5.99(Ads)/$11.99(No Ads) per month"},
      	  {:title => 'Silence', :rating => 'Hulu', :release_date => '13-Jan-2017', :imgurl => 'silence.jpg', :favcounter => 0, :description => "When the world is under attack from terrifying creatures who hunt their human prey by sound, 16-year old Ally Andrews (Kiernan Shipka), who lost her hearing at 13, and her family seek refuge in a remote haven.", :price => "$5.99(Ads)/$11.99(No Ads) per month"},   
      	  {:title => 'Shoplifters', :rating => 'Hulu', :release_date => '23-Nov-2018', :imgurl => 'shoplifters.jpg', :favcounter => 0, :description => "A family of small-time crooks take in a child they find outside in the cold.", :price => "$5.99(Ads)/$11.99(No Ads) per month"},
      	  {:title => 'Assassination Nation', :rating => 'Hulu', :release_date => '21-Sep-2018', :imgurl => 'assassination_nation.jpg', :favcounter => 0, :description => "", :price => "$5.99(Ads)/$11.99(No Ads) per month"},
      	  {:title => 'Fyre Fraud', :rating => 'Hulu', :release_date => '14-Jun-2019', :imgurl => 'fyre_fraud.jpg', :favcounter => 0, :description => "After a malicious data hack exposes the secrets of the perpetually American town of Salem, chaos decends and four girls must fight to survive, while coping with the hack themselves.", :price => "$5.99(Ads)/$11.99(No Ads) per month"},
      	  {:title => 'A Quiet Place', :rating => 'PrimeVideo', :release_date => '6-Apr-2018', :imgurl => 'quiet_place.jpg', :favcounter => 0, :description => "In a post-apocalyptic world, a family is forced to live in silence while hiding from monsters with ultra-sensitive hearing.", :price => "$12.99 a month/ Free with Amazon Prime"},
      	  {:title => 'It Comes At Night', :rating => 'PrimeVideo', :release_date => '9-Jun-2017', :imgurl => 'it_comes_at_night.jpg', :favcounter => 0, :description => "Secure within a desolate home as an unnatural threat terrorizes the world, a man has established a tenuous domestic order with his wife and son. Then a desperate young family arrives seeking refuge.", :price => "$12.99 a month/ Free with Amazon Prime"},
      	  {:title => 'MHA: Two Heroes', :rating => 'PrimeVideo', :release_date => '25-Sep-2018', :imgurl => 'two_heroes.jpg', :favcounter => 0, :description => "All Might and Deku accept an invitation to visit I Island where they battle against a villain who takes the island hostage.", :price => "$12.99 a month/ Free with Amazon Prime"},
      	  {:title => 'City of Ghosts', :rating => 'PrimeVideo', :release_date => '21-Jul-2017', :imgurl => 'city_of_ghosts.jpg', :favcounter => 0, :description => "A documentary that follows the efforts of \"Raqqa Is Being Slaughtered Silently,\" a handful of anonymous activists who banded together after their homeland was taken over by ISIS in 2014. With deeply personal access, this is the story of a brave group of citizen journalists as they face the realities of life undercover, on the run, and in exile, risking their lives to stand up against one of the greatest evils in the world today.", :price => "$12.99 a month/ Free with Amazon Prime"},
      	  {:title => 'Arrival', :rating => 'PrimeVideo', :release_date => '12-Nov-2016', :imgurl => 'arrival.jpg', :favcounter => 0, :description => "A linguist works with the military to communicate with alien lifeforms after twelve mysterious spacecraft appear around the world.", :price => "$12.99 a month/ Free with Amazon Prime"},
      	  {:title => 'Zama', :rating => 'PrimeVideo', :release_date => '28-Sep-2017', :imgurl => 'zama.jpg', :favcounter => 0, :description => "Based on the novel by Antonio Di Benedetto written in 1956, on Don Diego de Zama, a Spanish officer of the seventeenth century settled in Asunción, who awaits his transfer to Buenos Aires.", :price => "$12.99 a month/ Free with Amazon Prime"},
      	  {:title => 'The Thinning', :rating => 'Youtube', :release_date => '12-Oct-2016', :imgurl => 'thinning.jpg', :favcounter => 0, :description => "\"The Thinning\" takes place in a future plagued by overcrowding where population control is dictated by a high-school aptitude test. When two students (Logan Paul and Peyton List) discover the test is smoke and mirrors hiding a larger conspiracy, they must fight the system to expose it and take it down.", :price => "$9.99 a month"},
      	  {:title => 'Holmes and Watson', :rating => 'Youtube', :release_date => '24-Dec-2018', :imgurl => 'holmes.jpg', :favcounter => 0, :description => "A humorous take on Sir Arthur Conan Doyle's classic mysteries featuring Sherlock Holmes and Doctor Watson.", :price => "$9.99 a month"},
      	  {:title => 'Glass', :rating => 'Youtube', :release_date => '18-Jan-2019', :imgurl => 'glass.jpg', :favcounter => 0, :description => "Security guard David Dunn uses his supernatural abilities to track Kevin Wendell Crumb, a disturbed man who has twenty-four personalities.", :price => "$9.99 a month"},
      	  {:title => 'Escape Room', :rating => 'Youtube', :release_date => '4-Jan-2019', :imgurl => 'escape_room.jpg', :favcounter => 0, :description => "Six strangers find themselves in a maze of deadly mystery rooms, and must use their wits to survive.", :price => "$9.99 a month"}, 
      	  {:title => 'Into The Spiderverse', :rating => 'Youtube', :release_date => '14-Dec-2018', :imgurl => 'spiderverse.jpg', :favcounter => 0, :description => "Teen Miles Morales becomes Spider-Man of his reality, crossing his path with five counterparts from other dimensions to stop a threat for all realities.", :price => "$9.99 a month"},
      	  {:title => 'Vice', :rating => 'Youtube', :release_date => '25-Dec-2018', :imgurl => 'vice.jpg', :favcounter => 0, :description => "The story of Dick Cheney, an unassuming bureaucratic Washington insider, who quietly wielded immense power as Vice President to George W. Bush, reshaping the country and the globe in ways that we still feel today.", :price => "$9.99 a month"}
      	  
  	 ]

movies.each do |movie|
  Movie.create!(movie)
end
